[project]
name = "cognee-mcp"
version = "0.1.0"
description = "A MCP server project"
requires-python = ">=3.10"

dependencies = [
    "cognee[codegraph,gemini,huggingface]",
    "mcp==1.2.1",
    "uv>=0.6.3",
]

[build-system]
requires = [ "hatchling", ]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[project.scripts]
cognee = "src:main"
